services:
  backend:
    build: "backend"
    command: ["deno", "run", "--allow-net", "--watch", "server.ts"]
    volumes:
      - ./backend/src/:/app/:ro
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      DATABASE_PASSWORD: "softres"
      DATABASE_USER: "softres"
    depends_on:
      database:
        condition: "service_healthy"
  database:
    image: "postgres:18"
    environment:
      POSTGRES_PASSWORD: "softres"
      POSTGRES_USER: "softres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username softres"]
      interval: 1s
      timeout: 5s
      retries: 5
